### ISSUE TITLE
Settings Save Not Working

### ISSUE THREAD

**Issue by jsmylnycky** [Schamper/nodebb-plugin-shoutbox#101]
When I try to change anything on the config, then hit save, nothing happens.  I watched the network tab and theres no calls being made when the save button is hit.  It's impossible to change anything from the default.

**Comment by Schamper** [comment]
What version of NodeBB? And I assume the latest version of the shoutbox?

**Comment by jsmylnycky** [comment]
NodeBB 1.0.2 (I have a plugin holding me back from going to 1.1.0 right now that I still need to patch up), and the latest version of shoutbox.

**Comment by Schamper** [comment]
Any errors in the console?

**Comment by jsmylnycky** [comment]
Nope... I've tried both the latest version of Chrome and Firefox.  I cleared out my network and console logs after doing a full page reload on `/admin/plugins/shoutbox` and I see absolutely no errors.  When I click the Save button, there are no errors and no network activity.  It's almost like the click handler for the button isn't being activated.
