### ISSUE TITLE
Does not load in NodeBB V1.1.2

### ISSUE THREAD

**Issue by Holyphoenix** [Schamper/nodebb-plugin-shoutbox#102]
The shoutbox is no longer functional in V1.1.2.  I see these errors in my developer console in chrome.

nodebb.min.js?e4e45a06-5961-4179-a605-da944526b440:12 Uncaught ReferenceError: module is not defined(anonymous function) @ nodebb.min.js?e4e45a06-5961-4179-a605-da944526b440:12
nodebb.min.js?e4e45a06-5961-4179-a605-da944526b440:12 Uncaught TypeError: Cannot read property 'init' of undefined

**Comment by Schamper** [comment]
Got any more details? Working fine for me.
