### ISSUE TITLE
Error saving settings

### ISSUE THREAD

**Issue by tedr56** [Schamper/nodebb-plugin-shoutbox#71]
Thanks again for the 0.2.2 update.
The widget is now working in global/sidebar. :+1: 

You may be aware of that, but in widget side, all modifications returns "Error" "Error saving settings!"
This happens for minimize/maximize and the Sound & Notifications settings.

**Comment by Schamper** [comment]
Ah this is actually because I reworked how user settings work and forgot to reflect it on the widget side..

**Comment by Radiergummi** [comment]
Any update on this?

**Comment by Schamper** [comment]
Soon™

**Comment by Benderwan** [comment]
Is there any temporary workaround to this ?

**Comment by Schamper** [comment]
Fixed with v0.3.0.
