### ISSUE TITLE
Plugin does not work with 0.7.x

### ISSUE THREAD

**Issue by kurt-stolle** [Schamper/nodebb-plugin-shoutbox#76]
The plugin does not work with the latest version of NodeBB

**Comment by Aeternax** [comment]
I have it running fine with 0.7.x.
What errors are you getting?

**Comment by alesaint** [comment]
On my side that's work but I can't remove and edit message since 0.7.0

**Comment by Schamper** [comment]
New version is compatible with 0.9.x.
