### ISSUE TITLE
Two new features

### ISSUE THREAD

**Issue by 1ns** [Schamper/nodebb-plugin-shoutbox#80]
Hello!

First, thanks for hard work on this plugin, you have my respect.
Now, I have two suggestions for your plugin:
- Ability to change color shouts by users.
- An option in ACP to hide the shoutbox in certain areas or show only in configured areas.

**Comment by Schamper** [comment]
IMO colored shouts would become very annoying very quickly. I can stand behind a username colors depending on group though. I'll make a new issue about that myself.

Your second suggestion is kind of pointless given how this is a widget and is fully compatible with however you configure your widgets.

**Comment by 1ns** [comment]
My experiences with forums and shoutbox plugins they say that is inverse... but I respect a lot your opinion.
Colored shouts is an upgrade to constant conversation with lot of people and they with username colors shows the person's personality. (IMO, of course. hehehe)
