### ISSUE TITLE
Messing with profile layout

### ISSUE THREAD

**Issue by tedr56** [Schamper/nodebb-plugin-shoutbox#92]
Hey @Schamper,
Nice to see an update on the Shoutbox.
Thanks for the hard work.

I noticed a problem with the Shoutbox used in the Global Top Header.
All seems fine unless you access the profile layout.

Maybe it's theme related. I don't really know.

Thanks

**Comment by Schamper** [comment]
Do you have a screenshot?

**Comment by tedr56** [comment]
Sure

![screenshot from 2015-12-08 05 02 23](https://cloud.githubusercontent.com/assets/186070/11647506/1202adc8-9d69-11e5-9a59-c682e3be890a.png)

**Comment by tedr56** [comment]
I use the default persona theme

**Comment by Schamper** [comment]
Looks weird for sure but looks more like an issue with persona than the shoutbox. I'll see if I can look into it soon.

**Comment by Caes95** [comment]
Same problem too, I was posted this issue in persona-theme and they redirect me here.

**Comment by Schamper** [comment]
Seems to be fixed in the persona theme.
