### ISSUE TITLE
Shoutbox not working in mobile browsers

### ISSUE THREAD

**Issue by Radiergummi** [Schamper/nodebb-plugin-shoutbox#93]
When using a mobile browser (or DevTools), the shoutbox window stays blank:
<img width="570" alt="bildschirmfoto 2015-12-11 um 13 10 21" src="https://cloud.githubusercontent.com/assets/6115429/11743532/90a6161e-a008-11e5-9651-2a35fd280667.png">

These messages pop up in the console: 
<pre style="color:red">
Uncaught TypeError: <b>Cannot read property 'mouse' of undefined</b>
(anonymous function) @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:15
(anonymous function) @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:15

Uncaught TypeError: <b>Cannot read property 'addButtonDispatch' of undefined</b>
(anonymous function) @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:14
k.execCb @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:9
x.check @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
(anonymous function) @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
(anonymous function) @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
(anonymous function) @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
z @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
x.emit @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
x.check @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
x.enable @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
x.init @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
g @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:8
k.completeLoad @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:9
k.onScriptLoad @ nodebb.min.js?59d61621-9814-4a9d-ac66-aa781f0bd6b9:9
</pre>

I'm on NodeBB @ 0.9.1 and nodebb-plugin-shoutbox @ 3.1.

**Comment by Schamper** [comment]
Works fine on Edge on Windows 10 Mobile. Also had no reports of it not working on Android (presumable Chrome).

The error doesn't really look related to the shoutbox too, I never use those methods.
Do you still get those errors when the shoutbox is disabled?

**Comment by Radiergummi** [comment]
Well, I am experiencing this with a completely fresh installation of 0.9.1.. The errors only show up on the shoutbox page. Any idea why shouts might not be showing up? It's no CSS issue, the DOM elements don't appear at all.

**Comment by Schamper** [comment]
Javascript does this funny thing where it just halts execution of scripts on the page when there is an error. So there is something causing that error on the page which prevents the shoutbox from loading.

I believe running NodeBB with the `NODE_ENV=development` environment variable prevents the scripts from being minified. I suggest you try that to figure out what is causing the error.

**Comment by Radiergummi** [comment]
Okay, my bad - both errors show on any page, just overlooked them earlier. Seems to be a load order problem. I'll move this to the NodeBB repo. Thank you for the fast response though :blush:

**Comment by Schamper** [comment]
:+1:
