### ISSUE TITLE
Can't place Homepage

### ISSUE THREAD

**Issue by thelaw44** [Schamper/nodebb-plugin-shoutbox#94]
I am trying to place the shoutbox on top of the homepage but I could't do that. Is it not supported or I could't find the way?

**Comment by tedr56** [comment]
Hi.
You need to add the Shoutbox widget in the GlobalHeader.
Then add this to the custom CSS

```
.shoutbox {
    display: none;
}

.page-home .shoutbox {
    display: block;
}
```

**Comment by Schamper** [comment]
Ideally you would use a theme which has a widget block on the homepage, but I suppose the mentioned solution would also work.
